#!/bin/bash

FILENAME=/tmp/i3lock.png
IDLE_COLOR='#221A33'
VERIFICATION_COLOR='#A60121'
ERROR_COLOR='#FF3627'

scrot -B 5 $FILENAME
i3lock -i $FILENAME -o $VERIFICATION_COLOR -l $IDLE_COLOR -w $ERROR_COLOR
rm $FILENAME
